services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSWORD=C10searchengine
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=C10searchengine
      - PMA_HOST=mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql
